version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=cliy0a6y8002fqm9s7yfwelqw
